services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techeventradar_app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - eventradar_sock:/home/meto/TechEventRadar/eventradar.sock
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - db
    ports:
      - "5000:5000"
    # command: python app.py # Bu satırı da gunicorn komutuyla değiştirin
    command: gunicorn app:app --bind 0.0.0.0:5000 --workers 4

  db:
    image: postgres:16.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  db_data:
  eventradar_sock:
