"""add contact_email to event_requests

Revision ID: ccc17f460dba
Revises: f87bd78e167e
Create Date: 2026-05-26 15:36:54.024326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc17f460dba'
down_revision = 'f87bd78e167e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_requests', sa.Column('contact_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_requests', 'contact_email')
    # ### end Alembic commands ###


